
# OUTPUT
# Select the options of the data output 
# As there are several modules, settings have to be defined for each module, especially in SPECT, where there 
# are a lots of hits for only a few counts, so it's better to limit the amount of data produced
# Here the SingleDigi output can be used if you have your own program to process the data


# O U T P U T
/gate/output/root/disable
/gate/output/root/setFileName benchSPECT
/gate/output/root/setRootSinglesFlag 0 #new
/gate/output/root/setRootSinglesAdderFlag 0 
/gate/output/root/setRootSinglesBlurringFlag 0 
/gate/output/root/setRootSinglesSpblurringFlag 0
/gate/output/root/setRootSinglesThresholderFlag 0
/gate/output/root/setRootSinglesUpholderFlag 0

/gate/output/ascii/enable
/gate/output/ascii/setFileName gate
/gate/output/ascii/setOutFileHitsFlag 1 #new
/gate/output/ascii/setOutFileSinglesFlag 1 #new
/gate/output/ascii/setOutFileSinglesAdderFlag 0
/gate/output/ascii/setOutFileSinglesSpblurringFlag 0
/gate/output/ascii/setOutFileSinglesBlurringFlag 0
/gate/output/ascii/setOutFileSinglesThresholderFlag 0
/gate/output/ascii/setOutFileSinglesUpholderFlag 0

/gate/output/ascii/describe



# R A N D O M
# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName Ranlux64
#/gate/random/setEngineSeed default
#/gate/random/setEngineSeed auto
/gate/random/setEngineSeed 123456789
#/gate/random/resetEngineFrom fileName
/gate/random/verbose 1


# P R O J E C T I O N
# Makes a set of projections from the crystal hits
# Define the binning the projection module to be used
/gate/output/projection/enable #new
/gate/output/projection/setFileName gate #new
/gate/output/projection/pixelSizeX 2.5 mm
/gate/output/projection/pixelSizeY 2.5 mm
/gate/output/projection/pixelNumberX 128
/gate/output/projection/pixelNumberY 128

# Specify the projection plane (XY, YZ or ZX)
/gate/output/projection/projectionPlane ZX
