#----------------------------------------------------------------------#
#                   Source code developed by the                       #
#               Medical Image Processing Laboratory                    #
#                     (C) Copyright 2006-2010                          #
#      Department of Biomedical Engineering & Environmental Sciences   #
#               National Tsing Hua University,Taiwan                   #
#                       All Rights Reserved                            #
#----------------------------------------------------------------------#
#              Author            : muska                               #
#              Data last revised : 2008/3/14                           #
#              Data Originated   : 2008/3/13                           #
#              Purpose : Construct ECAT Accel parameter file of GATE   #
#                                                                      #
#              Reference         :                                     #
#----------------------------------------------------------------------#
                                           
#-----------------------oooooOOOOO00000OOOOOooooo----------------------#
#     D E F I N E   Y O U R   C O M P L E T E   S I M U L A T I O N    #
#              W I T H   8   S T E P S   A N D                         #
#          W I T H   8   S T A N D A R D   M A C R O S                 #
#-----------------------oooooOOOOO00000OOOOOooooo----------------------#

#----------------------------------------------------------------------#
#             	V I S U A L I S A T I O N                              #
#----------------------------------------------------------------------#
#/control/execute Visu.mac
/vis/disable

/gate/geometry/setMaterialDatabase GateMaterials.db


#----------------------------------------------------------------------#
#                           W O R L D                                  #
#----------------------------------------------------------------------#
/gate/world/geometry/setXLength 300 cm
/gate/world/geometry/setYLength 300 cm
/gate/world/geometry/setZLength 300 cm

#----------------------------------------------------------------------#
#             1).  S C A N N E R   G E O M E T R Y                     #
#----------------------------------------------------------------------#
/control/execute SPECT_Scanner.mac

#----------------------------------------------------------------------#
#             2).  P H A N T O M   G E O M E T R Y                     # 
#----------------------------------------------------------------------#
/control/execute Phantom.mac

#----------------------------------------------------------------------#
#             3).  P H Y S I C S   D E S C R I P T I O N               #
#----------------------------------------------------------------------#	
/control/execute Physics.mac

#----------------------------------------------------------------------#
#             4).  A C Q U I S I T I O N    P A R A M E T E R S        #
#----------------------------------------------------------------------# 
/control/execute Acquisition.mac

#----------------------------------------------------------------------#
#	              I N I T I A L I Z E                              #
#----------------------------------------------------------------------#
/gate/run/initialize


#----------------------------------------------------------------------#
#             5).  O U T P U T   D E F I N I T I O N                   #
#----------------------------------------------------------------------# 
/control/execute Output.mac

#----------------------------------------------------------------------#
#             6).  V E R B O S I T Y   L E V E L                       #
#----------------------------------------------------------------------# 	
/control/execute Verbose.mac

#----------------------------------------------------------------------#
#             7).  S O U R C E   D E F I N I T I O N                   #
#----------------------------------------------------------------------# 
/control/execute source.mac

#----------------------------------------------------------------------#
#             8).  S T A R T   A C Q U I S I T I O N                   #
#----------------------------------------------------------------------#	
/control/execute TimeManagement.mac
